// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsMicroservice.Models;

namespace ProductsMicroservice.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20191003134015_EFCoreCodeFirstSample.Models.ProductsContextSeed")]
    partial class EFCoreCodeFirstSampleModelsProductsContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsMicroservice.Models.Products", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Intel wirles keyboard",
                            Price = 20m,
                            ProductName = "Intel-Keyboard"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Intel wirles mouse",
                            Price = 20m,
                            ProductName = "Intel-Mouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
